#!/usr/bin/env node
/**
 * Runs after `elm-land build`. Writes dist/sw.js with a precache list derived
 * from dist/index.html (hashed bundles) plus known static trees under dist/.
 */
import crypto from 'crypto'
import fs from 'fs'
import path from 'path'

const distDir = path.resolve(process.cwd(), 'dist')

function walkFilesUnder(rootDir, relPrefix = '') {
  /** @returns {string[]} URL paths beginning with / */
  if (!fs.existsSync(rootDir)) return []
  const entries = fs.readdirSync(rootDir, { withFileTypes: true })
  const out = []
  for (const e of entries) {
    const rel = relPrefix ? `${relPrefix}/${e.name}` : e.name
    const abs = path.join(rootDir, e.name)
    if (e.isDirectory()) {
      out.push(...walkFilesUnder(abs, rel))
    } else if (!rel.endsWith('.map')) {
      out.push('/' + rel.split(path.sep).join('/'))
    }
  }
  return out
}

/** Same-origin URLs referenced in HTML (scripts, stylesheets, manifests). */
function urlsFromHtml(html) {
  const set = new Set()
  const re = /(?:src|href)=(["'])(\/[^"'#?\s]*)\1/g
  let m = re.exec(html)
  while (m) {
    if (m[2] !== '/sw.js') {
      set.add(m[2])
    }
    m = re.exec(html)
  }
  return set
}

function main() {
  if (!fs.existsSync(distDir)) {
    console.error('generate-sw.mjs: dist/ not found. Run elm-land build first.')
    process.exit(1)
  }

  const indexPath = path.join(distDir, 'index.html')
  const html = fs.readFileSync(indexPath, 'utf8')
  /** @type {Set<string>} */
  const urls = new Set(urlsFromHtml(html))

  for (const u of walkFilesUnder(path.join(distDir, 'images'), 'images')) {
    urls.add(u)
  }
  for (const u of walkFilesUnder(path.join(distDir, 'icons'), 'icons')) {
    urls.add(u)
  }

  for (const rel of ['style.css', 'manifest.webmanifest']) {
    if (fs.existsSync(path.join(distDir, rel))) {
      urls.add('/' + rel)
    }
  }

  urls.add('/')
  urls.add('/index.html')

  const sorted = [...urls].sort()

  const cacheKey = crypto.createHash('sha256').update(sorted.join('\n')).digest('hex').slice(0, 16)
  const cacheName = `fiber-empire-${cacheKey}`

  const body = `// Generated by scripts/generate-sw.mjs — do not edit manually
const CACHE_NAME = ${JSON.stringify(cacheName)}
const PRECACHE_URLS = ${JSON.stringify(sorted, null, 2)}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) =>
        Promise.all(PRECACHE_URLS.map((u) =>
          cache.add(u).catch((err) => {
            console.warn('[Fiber Empire SW] precache failed:', u, err)
          }),
        )),
      )
      .then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const { request } = event
  if (request.method !== 'GET') return

  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return

  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() => caches.match('/index.html')),
    )
    return
  }

  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached
      return fetch(request).then((res) => {
        if (res && res.ok && res.status === 200) {
          const copy = res.clone()
          caches.open(CACHE_NAME).then((cache) => cache.put(request, copy))
        }
        return res
      })
    }),
  )
})
`

  const outPath = path.join(distDir, 'sw.js')
  fs.writeFileSync(outPath, body)
  console.log(`Wrote ${path.relative(process.cwd(), outPath)} (${sorted.length} precache URLs, ${cacheName})`)
}

main()
